version: "3"

services:
  db:
    image: postgres
    container_name: "${POSTGRES_CONTAINER_NAME}"
    restart: always
    ports:
      - "${POSTGRES_HOST_MAP_PORT}:5432"
    expose:
      - "5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1m
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_HOST_MAP_PORT}:8080"

# connect docker postgresql from host
# psql -h localhost -p <host_map_port> -U <db_user> -W
