version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    env_file:
      - ./general.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

