version: "3"

services:
  redis:
    image: redis
    container_name: "${REDIS_CONTAINER_NAME}"
    restart: always
    ports:
      - "${REDIS_HOST_MAP_PORT}:6379"
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli ping | grep PONG" ]
      interval: 1m
      timeout: 10s
      retries: 3

# connect docker redis from host
# redis-cli <host_map_port>